version: '3.8'

services:
  app:
    build: .
    container_name: api_faturas_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - api_faturas_net

  db:
    image: postgres:16
    container_name: api_faturas_db
    restart: always
    environment:
      POSTGRES_DB: faturas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "BUD69{@rg#3^"
    ports:
      - "5440:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - api_faturas_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: api_faturas_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - api_faturas_net

volumes:
  db_data:

networks:
  api_faturas_net: